### ISSUE TITLE
Sequential numbers over 99999

### ISSUE THREAD

**Issue by marquezj** [IAEA-NDS/endf-parserpy#6]
I recently found that ENDF-parserpy goes beyond column 80 when the sequential number is above 99999. The [solution in NJOY](https://github.com/njoy/NJOY2016/blob/329f011c1c16e6adf37ed2da72497885b3a56534/src/endf.f90#L108) is to go back to 1. I am not sure if that is a proper solution, but at least it works within the 80 columns.

One possibility could be to make the sequential numbers optional in `endf_parserpy.EndfParser.write()` and `endf_parserpy.EndfParser.writefile()`.

**Comment by gschnabel** [comment]
> I recently found that ENDF-parserpy goes beyond column 80 when the sequential number is above 99999. The [solution in NJOY](https://github.com/njoy/NJOY2016/blob/329f011c1c16e6adf37ed2da72497885b3a56534/src/endf.f90#L108) is to go back to 1. I am not sure if that is a proper solution, but at least it works within the 80 columns.

The same strategy for dealing with sequential numbers has been implemented with fa8317a in the ```EndfParser``` class and with 728b302 for the C++ parser.

> One possibility could be to make the sequential numbers optional in endf_parserpy.EndfParser.write() and endf_parserpy.EndfParser.writefile().

I think this feature is useful in its own right. I've added an ```include_linenum``` argument to the ```EndfParser``` constructor to let the user control the addition of sequential numbers (fafc3f6). The same option is implemented for the C++ parser and associated ```EndfParserCpp``` class with 1b353df.
