### ISSUE TITLE
Cannot read EAF-2007 format

### ISSUE THREAD

**Issue by Radiation-Transport** [IAEA-NDS/endf-parserpy#7]
The parser seems not able to read the EAF-2007 format. This could be caused by its outdated format.
the tool can be adapted/modified in order to be compared some channels with TENDL-2017 which is released with FENDL3.2b.

![image](https://github.com/user-attachments/assets/75c154fc-0493-4ad5-b895-3f64746de186)

**Comment by gschnabel** [comment]
Thank you for reporting. I've never tested it on EAF-2007. It seems to be able to read all files  I tested on of EAF-2010 (after excluding MF40 from parsing due to ~11% of files likely having a formatting issue in MF40).

According to the error message, it seems that the TAPEID record is missing at the beginning of the file. Try to use the option `ignore_missing_tpid=True`:

```
parser = EndfParser(ignore_missing_tpid=True)
```

Please report back whether it solves the problem.

**Comment by Radiation-Transport** [comment]
Unfortunately, the same error appears.

**Comment by marquezj** [comment]
@Radiation-Transport: from the [documentation](https://www.oecd-nea.org/dbdata/data/manual-endf/EAF-format(Based_on_UKAEA-FUS-535).pdf) it appears that it is a special format based on ENDF-5. You might be able to read it if you create a custom recipe for MF=3 and MF=33.

**Comment by Radiation-Transport** [comment]
@marquezj thanks for this. So, no need to put effort in this quite old format. Do you know any available python parser?

**Comment by marquezj** [comment]
@Radiation-Transport, I meant modify the recipes in endf-parserpy to read them. 

It seems the EAF2007 format does not have MF=0/MT=0 section and then is a slightly modified MF=3 section which you could read by creating your own rule, using the ENDF-6 MF=3 recipe as a template:

https://github.com/IAEA-NDS/endf-parserpy/blob/main/endf_parserpy/endf_recipes/endf6/endf_recipe_mf3.py

I do not have EAF2007 myself, but it does not seem hard to do.

**Comment by gschnabel** [comment]
As @marquezj suggested, the ENDF MF=3 recipe can be updated to allow for reading the EAF-2007 library. Then, another issue is that all materials of the EAF-2007 are stored in a single file, which is currently not supported by endf-parserpy. However, it is possibly to split up the materials manually and then parse the chunks individually. Implementing this, I've also discovered another bug related to the `ignore_send_records` options which is now fixed on the `dev` branch. So, given that you are using a version with commit id 933cb3f or later on the `dev` branch, you can use the following code snippet:

```python
import os
import logging
from endf_parserpy import EndfParser
from endf_parserpy.endf_recipes.endf6 import endf_recipe_dictionary

# change MF3 recipe to support EAF-2007
endf_recipe_dictionary[3] = """
for i=1 to 2:
    [MAT, 3,MT / DESCRIPTION[i]]TEXT
endfor
[MAT, 3, MT/ ZA, AWR, 0, LFS, 0, 0] HEAD
[MAT, 3, MT/ QM, QI, 0, LR, NR, NP / E / xs]TAB1 (xstable)
SEND
"""
parser = EndfParser(
    recipes=endf_recipe_dictionary, ignore_missing_tpid=True,
    ignore_send_records=True, loglevel=logging.ERROR
)

# Alternatively, if using the endf-parserpy version on branch feature_eaf2007:
# parser = EndfParser(endf_format="eaf2007", ignore_missing_tpid=True, ignore_send_records=True, loglevel=logging.ERROR)
# parser = EndfParserCpp(endf_format="eaf2007", ignore_missing_tpid=True, ignore_send_records=True)

# read EAF-2007 file
with open("eaf_n_xs_20070", "r") as f:
    lines = f.readlines()

# split up the various materials
mat_dict = {}
for l in lines:
    curmat = int(l[66:70])
    if curmat > 0:
        curlines = mat_dict.setdefault(curmat, [])
        curlines.append(l)

# iterate over materials and parse each of those
parsed_mat_dict = {}
for matnr in mat_dict.keys():
    parsed_mat = parser.parse(mat_dict[matnr])
    parsed_mat_dict[matnr] = parsed_mat

# do something with the parsed materials,
# e.g. show variables in MF3/MT16 of MAT=102 
parsed_mat_dict[102][3][16].keys()
```

I am still undecided whether I want to add this use case only as an extra section to the documentation or to include the modified recipe in the pre-defined endf recipes. The issue with the latter option is that it adds another custom recipe dictionary that would also be compiled to C++ code during package installation (taking a while). I am doubtful that this compilation overhead is warranted for this very specific use case.

For the time being, if the code snippets above solves your parsing need, @Radiation-Transport, I will close this issue.

**Comment by dodu94** [comment]
Thanks for this Georg, it works as expected. If I were you I would not add it to the recipes but instead add a section in the doc since the format is quite old. Maybe what you could do is just handle the error that is thrown when trying to parse the EAF2007 format printing an error message that redirects the user to the appropriate doc section.
